# The URL the site will be built for
title = "tr1x_em"
description = "Welcome,here you can find more about me, oh and I write too!!"
base_url = "https://trix.is-a.dev"
author = "tr1x_em"

theme = "ametrine"
compile_sass = true
build_search_index = true
minify_html = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [
  { name = "tags", feed = true, paginate_by = 10 },
  { name = "categories", feed = true },
]

[languages.hi]
title = "tr1x_em"
description = "स्वागत है, यहाँ आप मेरे बारे में और जान सकते हैं।"
generate_feeds = true
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
extra_syntaxes_and_themes = ["themes/ametrine/sublime"]
highlight_theme = "css"
highlight_themes_css = [
  { theme = "monokai-pro-dark", filename = "syntax-theme-dark.css" },
  { theme = "monokai-pro-light", filename = "syntax-theme-light.css" },
]
render_emoji = false
smart_punctuation = true
lazy_async_image = false
bottom_footnotes = true
external_links_class = "external"
github_alerts = true

[link_checker]
internal_level = "warn"

[search]
index_format = "elasticlunr_json"


[extra]
accent_color = ["hsl(5 100% 84%)", "hsl(4 48% 82%)"]
categories = [
  { name = "Archived", description = "Posts that have been archived due to their age.", color = "purple", icon = "box-arrow-down" },
  { name = "Featured", description = "Posts that are somewhat decently written.", color = "yellow", icon = "star" },
  { name = "Hot", description = "Posts that did numbers compared to others.", color = "red", icon = "fire" },
  { name = "Test", description = "Categories can be set and customized entirely from config, woo-hoo!", color = "green", icon = "feather" },
]

issues_url = "https://github.com/tr1xem/website/issues/new"
source_url = "https://github.com/tr1xem/website"
show_copy_button = true
show_reading_time = true
show_backlinks = true
date_format = "%d %B %Y"
date_format_long = "%d %B %Y, %R (%Z)"
date_locale = "en_IN"
timezone = "Asia/Kolkata"
show_comments_qr = true
csp = [
  { directive = "font-src", domains = [
    "'self'",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "https:",
    "data:",
  ] },
  { directive = "media-src", domains = [
    "'self'",
    "https:",
  ] },
  { directive = "script-src", domains = [
    "giscus.app",
  ] },
  { directive = "style-src", domains = [
    "giscus.app",
    "'self'",
    "'unsafe-inline'",
  ] },
  { directive = "frame-src", domains = [
    "www.youtube-nocookie.com",
    "*.atabook.org",
    "atabook.org",
    "incr.easrng.net",
    "vmst.io",
    "drive.google.com",
    "giscus.app",
  ] },
  { directive = "connect-src", domains = [
  "cafe.frizzbees.dev",
    "*.umami.dev",
    "cloud.umami.is",
    "status.cafe",
    "api.lanyard.rest",
    "ws.audioscrobbler.com",
    "discord.com",
    "api.github.com",
    "ntfy.sh",
  ] },
  { directive = "base-uri", domains = [
    "'none'",
  ] },
  { directive = "form-action", domains = [
    "'none'",
  ] },
]

[extra.hi]
font = "fonts/mangal.ttf"
[extra.meta]
favicon = "favicon.ico"
card = "banner.png"


[extra.nav]
icon = "logo.png"
# Usage of an icon is heavily adviced. In case if none is provided, first two
# letters of the link name will be used instead.
# Any icon name from https://phosphoricons.com can be used.
links = [
  { name = "Writing", category = [
    { url = "@/blog/_index.md", name = "Blog", icon = "newspaper-clipping" },
    { url = "@/nanolog/_index.md", name = "Nanolog", icon = "note-pencil" },
    { url = "@/guestbook/_index.md", name = "Guestbook", icon = "envelope-open" },
    { url = "@/tutorials/_index.md", name = "Tutorials", icon = "screwdriver" },

  ] },
    { name = "More about me", category = [
		{ url = "@/blog/2025-09-22-coding-principles/index.md", name = "Coding Principles", icon = "code" },
		{ url = "@/blog/2025-12-13-my-dev-setup-is-better-than-yours/index.md", name = "Dev Workflow", icon = "linux-logo" },
	] },
]

[extra.nav.hi]
icon = "logo.png"
# Usage of an icon is heavily adviced. In case if none is provided, first two
# letters of the link name will be used instead.
# Any icon name from https://phosphoricons.com can be used.
links = [
  { name = "लेखन", category = [
    { url = "@/blog/_index.md", name = "ब्लॉग", icon = "newspaper-clipping" },
    { url = "@/nanolog/_index.md", name = "नैनोलॉग", icon = "note-pencil" },
    { url = "@/guestbook/_index.md", name = "गेस्टबुक", icon = "envelope-open" },
    { url = "@/tutorials/_index.md", name = "ट्यूटोरियल्स", icon = "screwdriver" },
  ] },

  { name = "मेरे बारे में और", category = [
    { url = "@/blog/2025-09-22-coding-principles/index.md", name = "कोडिंग सिद्धांत", icon = "code" },
    { url = "@/blog/2025-12-13-my-dev-setup-is-better-than-yours/index.md", name = "डेव वर्कफ़्लो", icon = "linux-logo" },
  ] },
]

[extra.footer]
# copyright = true
show_fediring = true
copyright = "© tr1x_em, 2021-$YEAR"
show_timestamp = true
show_powered_by = true
socials = [
    { url = "https://discord.com/users/885063317079592961", icon = "discord" },
    { url = "https://github.com/tr1xem", icon = "github" },
    { url = "https://reddit.com/u/l_lawliet_9999", icon = "reddit" },
    { url = "https://x.com/tr1x_em", icon = "x" },
    { url = "mailto:admin@trix.is-a.dev", icon = "gmail" },
]

[extra.footer.hi]
copyright = "© tr1x_em, 2021-$YEAR"

[extra.fediverse]
# Fediverse integration.
# Used for:
# - Commenting
# - Custom emoji shortcode
# - Website verification
# - Author attribution
#
# Mastodon-powered commenting is based on
# https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/
#
# Values can be overridden in the front-matter, e.g.
# for multi-author blogs or guest posts.

host = "mastodon.social"
user = "tr1x_em"


[extra.debug]
layout = false
no_styles = false
no_emojis = false

